<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
  public function findAllOrderedByDate()
{
    return $this->getEntityManager()
        ->createQuery(
            'SELECT * FROM AppBundle:Post ORDER BY createAt DESC LIMIT 3'
        )
        ->getResult();
}
}
